"""The migrations build exactly the schema the models describe, checked from an empty database.

WHY THIS EXISTS

`alembic revision --autogenerate` diffs a database against the metadata `alembic/env.py` gets by
importing `src.models`. On 2026-09-17, `alembic check` against a database freshly upgraded to head
reported DROP TABLE for `credit_vouchers`, `gpu_slots` and `gpu_queue_tickets`. Those are live
voucher and queue tables. Their models existed but were never imported in `models/__init__.py`, so
the next autogenerated migration would have dropped them in one line nobody reads. It also reported
the five operations `6c5c1ed2861e` had already cut out of an autogenerated migration by hand, which
were still unresolved. Nothing failed, because nothing runs autogenerate until somebody writes a
migration.

WHY ALEMBIC RUNS IN A SUBPROCESS

In-process, `Base.metadata` holds every model that any collected test module has imported.
`test_vouchers_postgres.py` imports `src.models.credit_voucher` directly, so in a full-suite run
the table this test exists for would already be registered and the check would pass. A fresh
interpreter builds the metadata the way `env.py` does and in no other way.

WHY A SCRATCH DATABASE, AND WHY THE PASS IS CHECKED ON IT

Only an upgrade from empty shows that the migrations alone produce what the models describe. The
suite's usual database is shared with rows other tests create, so each run creates and drops its
own uniquely named database instead.

`alembic.ini` falls back to the dev database. If `env.py` ever stopped reading `DATABASE_URL_SYNC`,
both commands would run against a database already at head and pass without checking anything
this test set up. So the test also reads `alembic_version` from the scratch database, to show the
upgrade really ran there.
"""

import os
import subprocess
import sys
import uuid
from pathlib import Path

import pytest
from conftest import TEST_DATABASE_URL, requires_postgres
from sqlalchemy import create_engine, text
from sqlalchemy.engine import make_url
from sqlalchemy.pool import NullPool

pytestmark = [requires_postgres]

API_ROOT = Path(__file__).resolve().parents[1]


def _sync_url(database: str) -> str:
    """`TEST_DATABASE_URL`'s server, on the psycopg2 driver `env.py` uses, for another database."""
    url = make_url(TEST_DATABASE_URL).set(drivername="postgresql", database=database)
    return url.render_as_string(hide_password=False)


@pytest.fixture
def scratch_database_url():
    name = f"voidcode_migration_check_{uuid.uuid4().hex[:12]}"
    # CREATE DATABASE cannot run inside a transaction.
    admin = create_engine(_sync_url("postgres"), isolation_level="AUTOCOMMIT", poolclass=NullPool)
    with admin.connect() as conn:
        conn.execute(text(f'CREATE DATABASE "{name}"'))
    try:
        yield _sync_url(name)
    finally:
        with admin.connect() as conn:
            conn.execute(text(f'DROP DATABASE IF EXISTS "{name}" WITH (FORCE)'))
        admin.dispose()


def _alembic(database_url: str, *args: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-m", "alembic", *args],
        cwd=API_ROOT,
        env={**os.environ, "DATABASE_URL_SYNC": database_url},
        capture_output=True,
        text=True,
        # A connection that never answers should fail the test, not hang the suite.
        timeout=300,
    )


def test_autogenerate_finds_nothing_after_a_fresh_upgrade(scratch_database_url):
    upgrade = _alembic(scratch_database_url, "upgrade", "head")
    assert upgrade.returncode == 0, (
        f"alembic upgrade head failed:\n{upgrade.stdout}{upgrade.stderr}"
    )

    engine = create_engine(scratch_database_url, poolclass=NullPool)
    try:
        with engine.connect() as conn:
            versions = conn.execute(text("SELECT version_num FROM alembic_version")).scalars().all()
    finally:
        engine.dispose()
    assert versions, "the upgrade did not run against the scratch database"

    check = _alembic(scratch_database_url, "check")
    output = check.stdout + check.stderr
    assert check.returncode == 0 and "No new upgrade operations detected" in output, (
        "The models and the migrations disagree. `alembic revision --autogenerate` would emit the "
        "operations below.\n"
        "  * A removed table usually means its model is not imported in src/models/__init__.py.\n"
        "  * Anything else: change the model to match the migration that shipped, or write a "
        "migration if the schema really has to change.\n\n" + output
    )
