/**
 * Generate the application icon — `build/icon.svg` and `build/icon.png` — from one set of numbers.
 *
 * WHY A GENERATOR RATHER THAN TWO COMMITTED FILES. electron-builder derives `.ico`, `.icns` and the
 * Linux PNG set from a single `build/icon.png`, so the raster is what actually ships. But a raster is
 * unreviewable in a diff, and an SVG beside it that nobody regenerates drifts. Emitting both from the
 * constants below means the reviewable file and the shipped file cannot disagree.
 *
 * WHY NOT RENDER THE EXISTING ART. Neither source is usable as an app icon:
 *
 *   - `renderer/src/app/icon.svg` switches stroke colour on `prefers-color-scheme`. An app icon is
 *     composited against taskbar and dock chrome the app does not know the colour of, and macOS wants
 *     a static raster. A media query cannot help there.
 *   - `renderer/src/components/brand/Mark.tsx` strokes `currentColor`, which has no parent to inherit
 *     from outside a document.
 *
 * A stroke-only ring on transparency also disappears against a taskbar of the wrong shade, so the
 * mark sits on the app's own `#0b0b0e` — the same value `windows.ts` gives `backgroundColor`, so the
 * icon and the window it opens read as one product.
 *
 * WHY NO DEPENDENCY. `sharp`, `png-to-ico` and `iconutil` are all avoidable: a ring is a distance
 * function, so rasterising it exactly is easier than depending on a native module, and the PNG
 * container is a signature plus three chunks. Deterministic too — no Skia or libpng version can
 * change the bytes, which matters because the output is committed.
 *
 * THIS IS THE THIRD COPY OF THIS GEOMETRY. `Mark.tsx` and `renderer/src/app/icon.svg` are the other
 * two, and both say the same thing: change one, change the others. The numbers here are that geometry
 * scaled to a 1024 canvas.
 *
 *   node scripts/render-icon.mjs
 */
import fs from "node:fs";
import path from "node:path";
import zlib from "node:zlib";
import { fileURLToPath } from "node:url";

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), "..");

// ── Geometry ────────────────────────────────────────────────────────────────
//
// The mark is r=10, stroke-width 5, so an outer diameter of 25 in a 32 viewBox. Scaled here to an
// outer diameter of ~62% of the canvas, which is the usual share for a centred glyph — enough
// presence at 1024, still readable once Windows renders it into 16px.

/** Canvas edge. 1024 because electron-builder wants that for the macOS `.icns` set. */
const SIZE = 1024;
const CENTRE = SIZE / 2;
/** Ring centreline radius and stroke width, in the mark's 10:5 proportion. */
const RADIUS = 254;
const STROKE = 127;
/** The gap, in degrees, bisected by 270° — straight up in SVG's y-down space. */
const GAP = 52;
/** Corner radius. ~17.6% of the edge, close to the platform convention for a squircle. */
const CORNER = 180;

const BACKGROUND = [11, 11, 14]; // #0b0b0e — windows.ts backgroundColor
const FOREGROUND = [255, 255, 255];

const GAP_FROM = 270 - GAP / 2; // 244
const GAP_TO = 270 + GAP / 2; // 296

// ── SVG ─────────────────────────────────────────────────────────────────────

/** Arc endpoint at `degrees`, in the same y-down convention as `Mark.tsx`. */
function endpoint(degrees) {
  const radians = (degrees * Math.PI) / 180;
  const round = (n) => Number(n.toFixed(3));
  return [round(CENTRE + RADIUS * Math.cos(radians)), round(CENTRE + RADIUS * Math.sin(radians))];
}

function svg() {
  const [x1, y1] = endpoint(GAP_TO);
  const [x2, y2] = endpoint(GAP_FROM);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${SIZE} ${SIZE}" width="${SIZE}" height="${SIZE}">
  <!--
    GENERATED by scripts/render-icon.mjs. Edit the constants there, not this file.

    The application icon: the aperture ring from components/brand/Mark.tsx on the app's own
    background. Same geometry in the mark's proportions — ${GAP} degree gap bisected by 270, butt
    caps, large-arc-flag 1 because the drawn arc is ${360 - GAP} degrees and so over 180,
    sweep-flag 1 for clockwise.

    Deliberately not currentColor and deliberately not transparent: see the generator's header.
  -->
  <rect width="${SIZE}" height="${SIZE}" rx="${CORNER}" ry="${CORNER}" fill="rgb(${BACKGROUND.join(",")})" />
  <path
    d="M${x1} ${y1}A${RADIUS} ${RADIUS} 0 1 1 ${x2} ${y2}"
    fill="none"
    stroke="rgb(${FOREGROUND.join(",")})"
    stroke-width="${STROKE}"
    stroke-linecap="butt"
  />
</svg>
`;
}

// ── PNG ─────────────────────────────────────────────────────────────────────

/** Inside the rounded rectangle covering the whole canvas. */
function inBackground(x, y) {
  const nx = Math.min(x, SIZE - x);
  const ny = Math.min(y, SIZE - y);
  if (nx < 0 || ny < 0) return false;
  if (nx >= CORNER || ny >= CORNER) return true;
  // Within a corner box: inside only if inside the corner's quarter-circle.
  const dx = CORNER - nx;
  const dy = CORNER - ny;
  return dx * dx + dy * dy <= CORNER * CORNER;
}

/**
 * On the drawn arc.
 *
 * The angle test *is* the butt cap: it cuts the stroke radially at each end and extends it by
 * nothing, which is what `stroke-linecap="butt"` means. Round caps would eat half a stroke width at
 * each end and very nearly close the gap once the icon is scaled down — `Mark.tsx` records measuring
 * exactly that.
 */
function inRing(x, y) {
  const dx = x - CENTRE;
  const dy = y - CENTRE;
  const distance = Math.hypot(dx, dy);
  if (Math.abs(distance - RADIUS) > STROKE / 2) return false;

  let degrees = (Math.atan2(dy, dx) * 180) / Math.PI;
  if (degrees < 0) degrees += 360;
  return degrees <= GAP_FROM || degrees >= GAP_TO;
}

/** 4x4 supersampling. Every feature here is a curve, so unsampled edges stair-step visibly. */
const SAMPLES = 4;

function pixels() {
  const data = Buffer.alloc(SIZE * SIZE * 4);
  const step = 1 / SAMPLES;
  const offset = step / 2;
  const total = SAMPLES * SAMPLES;

  for (let y = 0; y < SIZE; y += 1) {
    for (let x = 0; x < SIZE; x += 1) {
      let background = 0;
      let ring = 0;
      for (let sy = 0; sy < SAMPLES; sy += 1) {
        for (let sx = 0; sx < SAMPLES; sx += 1) {
          const px = x + offset + sx * step;
          const py = y + offset + sy * step;
          if (!inBackground(px, py)) continue;
          background += 1;
          if (inRing(px, py)) ring += 1;
        }
      }
      if (background === 0) continue;

      // Composite the ring over the background *within* the covered fraction, so a pixel on the
      // rounded corner and a pixel on the ring edge both blend correctly.
      const ringShare = ring / background;
      const i = (y * SIZE + x) * 4;
      for (let c = 0; c < 3; c += 1) {
        data[i + c] = Math.round(BACKGROUND[c] * (1 - ringShare) + FOREGROUND[c] * ringShare);
      }
      data[i + 3] = Math.round((background / total) * 255);
    }
  }
  return data;
}

const CRC_TABLE = (() => {
  const table = new Int32Array(256);
  for (let n = 0; n < 256; n += 1) {
    let c = n;
    for (let k = 0; k < 8; k += 1) c = c & 1 ? 0xedb88320 ^ (c >>> 1) : c >>> 1;
    table[n] = c;
  }
  return table;
})();

function crc32(buffer) {
  let c = -1;
  for (const byte of buffer) c = CRC_TABLE[(c ^ byte) & 0xff] ^ (c >>> 8);
  return (c ^ -1) >>> 0;
}

function chunk(type, data) {
  const length = Buffer.alloc(4);
  length.writeUInt32BE(data.length);
  const body = Buffer.concat([Buffer.from(type, "ascii"), data]);
  const crc = Buffer.alloc(4);
  crc.writeUInt32BE(crc32(body));
  return Buffer.concat([length, body, crc]);
}

function png() {
  const ihdr = Buffer.alloc(13);
  ihdr.writeUInt32BE(SIZE, 0);
  ihdr.writeUInt32BE(SIZE, 4);
  ihdr[8] = 8; // bit depth
  ihdr[9] = 6; // colour type: RGBA
  // 10..12 are compression, filter and interlace methods, all 0 — the only values PNG defines.

  const raw = pixels();
  // Filter type 0 per scanline. A real encoder would try the other four; the gain on a two-colour
  // image is not worth the code, and zlib already sees long runs.
  const stride = SIZE * 4 + 1;
  const scanlines = Buffer.alloc(stride * SIZE);
  for (let y = 0; y < SIZE; y += 1) {
    scanlines[y * stride] = 0;
    raw.copy(scanlines, y * stride + 1, y * SIZE * 4, (y + 1) * SIZE * 4);
  }

  return Buffer.concat([
    Buffer.from([0x89, 0x50, 0x4e, 0x47, 0x0d, 0x0a, 0x1a, 0x0a]),
    chunk("IHDR", ihdr),
    chunk("IDAT", zlib.deflateSync(scanlines, { level: 9 })),
    chunk("IEND", Buffer.alloc(0)),
  ]);
}

// ── Emit ────────────────────────────────────────────────────────────────────

const svgPath = path.join(root, "build/icon.svg");
const pngPath = path.join(root, "build/icon.png");

fs.mkdirSync(path.dirname(svgPath), { recursive: true });
fs.writeFileSync(svgPath, svg());
fs.writeFileSync(pngPath, png());

const outer = 2 * RADIUS + STROKE;
console.log(`icon: ${SIZE}x${SIZE}, ring outer ${outer} (${((outer / SIZE) * 100).toFixed(1)}% of canvas)`);
console.log(`  build/icon.svg`);
console.log(`  build/icon.png  ${(fs.statSync(pngPath).size / 1024).toFixed(1)} KB`);
