/**
 * Each legal document still hashes to the number committed beside it.
 *
 * WHY A DIGEST AND NOT A COMPARISON. `tests/test_marketing_pages.py` compares the application's
 * copy of each document with the website's, character for character. That works only while both
 * trees are in one checkout, and the website is being extracted into its own repository — at which
 * point that test has no second tree to read. One committed number per document replaces it: each
 * repository hashes its own copy against the same constant, and neither reads the other.
 *
 * THIS FILE IS THE SOURCE REPOSITORY'S HALF. It fails when the text moves without the constant, so
 * the digest cannot silently fall behind the document it pins. The website's own CI runs the mirror
 * of it against its own copy; `apps/web/src/lib/legal.ts` is generated by
 * `scripts/sync_web_legal.py` so that copy travels with the text.
 *
 * THE EXTRACTION RULE IS COPIED DELIBERATELY, not shared. It is `sections_of()` in
 * `test_marketing_pages.py`, and it has to be reproduced here in a second language: the digest is
 * only meaningful if both sides agree on which characters it covers. Restating it in three places
 * is the cost of the two copies being independent, and each restatement carries this note so the
 * next person changes all of them or none.
 */
import { describe, it, expect } from "vitest";
import { createHash } from "node:crypto";
import { readFileSync, existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { PRIVACY_SECTIONS_SHA256, TERMS_SECTIONS_SHA256 } from "@shared/legal";

const root = path.dirname(fileURLToPath(new URL("../package.json", import.meta.url)));
const OPEN = "const SECTIONS: Section[] = [";
const CLOSE = "// ── Sub-components";

/**
 * The document's text, and nothing around it.
 *
 * Carriage returns go because the two checkouts can disagree about line endings while the words do
 * not. Python's `read_text` translates every ending to LF and then strips CR; this strips CR from
 * the raw bytes. Those agree as long as no lone CR exists in the file, which `legal.ts` records as
 * verified and the first test below re-checks rather than trusting.
 */
function sectionsOf(file: string): string {
  const source = readFileSync(file, "utf8");
  expect(source, `${file} has no SECTIONS array`).toContain(OPEN);
  const afterOpen = source.slice(source.indexOf(OPEN) + OPEN.length);
  const end = afterOpen.indexOf(CLOSE);
  expect(end, `${file} has no ${CLOSE} marker`).toBeGreaterThan(-1);
  return afterOpen.slice(0, end).replace(/\r/g, "");
}

const DOCUMENTS = [
  ["PrivacyClient.tsx", PRIVACY_SECTIONS_SHA256],
  ["TermsClient.tsx", TERMS_SECTIONS_SHA256],
] as const;

describe("the legal documents match their committed digests", () => {
  it("contains no lone carriage return, which is what makes the two rules equivalent", () => {
    for (const [name] of DOCUMENTS) {
      const raw = readFileSync(path.join(root, "renderer/src/components/Legal", name));
      // Drop every CRLF pair, then look for what is left. A survivor would mean Python's universal
      // newlines turn it into LF while this file deletes it, and the two digests would differ for a
      // reason nobody would find quickly.
      const lone = raw.toString("binary").replace(/\r\n/g, "").split("\r").length - 1;
      expect(lone, `${name} contains a lone CR`).toBe(0);
    }
  });

  for (const [name, expected] of DOCUMENTS) {
    it(`${name} hashes to its constant`, () => {
      const text = sectionsOf(path.join(root, "renderer/src/components/Legal", name));
      const actual = createHash("sha256").update(text, "utf8").digest("hex");

      expect(
        actual,
        `${name}'s text has changed and its digest has not.\n` +
          `  If the change was intended, put this in src/shared/legal.ts:\n` +
          `    ${actual}\n` +
          "  and run `python scripts/sync_web_legal.py` so the website's copy moves with it."
      ).toBe(expected);
    });
  }

  it("covers the text and not the chrome around it", () => {
    /*
     * A positive control on the extraction, because a rule that returned "" would make every
     * assertion above agree on the hash of nothing.
     *
     * The two ends are asserted by content: section 1's id must be inside, and THE BREADCRUMB must
     * be outside. The breadcrumb is the right thing to check because it is precisely what the two
     * copies disagree about — `href="/profile"` here, `href="/"` on the website, since the
     * application's Settings screen does not exist there. If it fell inside the digest, the two
     * copies could never hash the same and the whole mechanism would be unusable.
     *
     * NOT "Last updated", which was the first attempt and was wrong: section 12's prose says "This
     * page carries a 'Last updated' date", so the phrase appears INSIDE the digest as well as in
     * the footer outside it. The assertion passed for the footer and failed on the sentence about
     * it — a reminder that these are documents, and a marker chosen from the rendering can also be
     * something the text talks about.
     */
    const privacy = sectionsOf(path.join(root, "renderer/src/components/Legal/PrivacyClient.tsx"));
    expect(privacy.length).toBeGreaterThan(5_000);
    expect(privacy, "section 1's own id is not inside the digest").toContain('id: "overview"');
    expect(privacy, "6.4 is not inside the digest").toContain("One way in, and why");
    expect(privacy, "the breadcrumb is inside the digest, so the two copies could never agree")
      .not.toContain('href="/profile"');
  });

  it("is mirrored into the website's tree, so the copy can check itself after the split", () => {
    /*
     * `apps/web/src/lib/legal.ts` is generated, not hand-written — the website has no way to import
     * from `desktop/` and will shortly be a different repository entirely. If this file is missing,
     * the extracted repository has no number to check its own copy against and the parity mechanism
     * silently becomes one-sided.
     */
    const mirrored = path.join(root, "..", "apps/web/src/lib/legal.ts");
    if (!existsSync(mirrored)) {
      throw new Error(
        "apps/web/src/lib/legal.ts is missing — run `python scripts/sync_web_legal.py`"
      );
    }
    const source = readFileSync(mirrored, "utf8");
    expect(source).toContain(PRIVACY_SECTIONS_SHA256);
    expect(source).toContain(TERMS_SECTIONS_SHA256);
  });
});
