"""Publish the landing page's demo snippet, so the website can render the real template.

WHY THIS EXISTS

`tests/test_catalog_coverage.py` asserted that the website's `defaultCode` was character-for-
character the `stable-softmax` template from `content/problems/stable-softmax.yaml`. Its reasoning
holds and is worth quoting, because it is the reason this is exported rather than dropped:

    "it is read by the landing page's demo, which is now the first VoidCode code a visitor ever
    sees, so it gets an assertion instead of a comment asking nicely"

    "the learner sees one thing and the grader another"

The website is a separate repository now, so that comparison has no second tree to read. This is the
third thing published the same way as the legal digests and the credit packs: exported here, checked
against the catalogue here, and checked against the page there.

WHY THE TEXT AND NOT A DIGEST

The website has to RENDER it. A hash would tell it whether its copy was right without telling it
what to render, so the contract carries the template and the check is that the template still
matches the catalogue. Nine lines; the cost of carrying it is nothing.

WHY IT MUST BE A COPY AT ALL

The demo renders before any request resolves, so it cannot be fetched. That was true inside the
monorepo too — the difference now is only that the copy lives in another repository.
"""

from __future__ import annotations

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TARGET = ROOT / "contracts/demo-snippet.json"

#: The catalogue problem the landing page demonstrates.
SLUG = "stable-softmax"


def snippet() -> dict[str, object]:
    # Imported here rather than at module scope so `--help`-style use and import errors stay
    # separable; `features.content` reads every problem YAML in the repository.
    import sys

    if str(ROOT) not in sys.path:
        sys.path.insert(0, str(ROOT))
    from features.content import load_raw

    problem = load_raw()[SLUG]
    templates = problem["code_templates"]
    assert templates, f"{SLUG} has no code templates"
    template = templates[0]["template_code"]
    assert isinstance(template, str) and template.strip(), f"{SLUG}'s first template is empty"
    return {
        "slug": SLUG,
        "title": problem.get("title", ""),
        "language": templates[0].get("language", "python"),
        "template_code": template,
    }


HEADER = {
    "//": (
        "GENERATED by scripts/export_demo_snippet.py from content/problems/stable-softmax.yaml. "
        "Do not edit. The website's landing page renders this as its demo — the first VoidCode code "
        "a visitor ever sees — and it must be the template the grader actually gives out, or the "
        "learner sees one thing and the grader another. This repository checks the file against the "
        "catalogue; the website checks its page against its copy of the file."
    )
}


def export() -> Path:
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    body = dict(HEADER)
    body.update(snippet())
    TARGET.write_text(json.dumps(body, indent=2) + "\n", encoding="utf-8", newline="\n")
    return TARGET


if __name__ == "__main__":
    written = export()
    data = json.loads(written.read_text(encoding="utf-8"))
    print(f"wrote {written.relative_to(ROOT).as_posix()}")
    print(f"  {data['slug']} ({data['language']}), {len(data['template_code'])} characters")
