"""Write the website's own copy of the legal digests and the version it displays.

Run by `sync_web_legal.py` after it copies the documents across; importable so a test can call it.

WHY THE WEBSITE NEEDS ITS OWN COPY OF THESE NUMBERS

`tests/test_marketing_pages.py` compares the application's copy of each legal document with the
website's, character for character. That works only while both trees are in one checkout. The
website is being extracted into its own repository, at which point that test has no second tree to
read — so each repository has to be able to check its own copy on its own, against one committed
number per document.

The website cannot import from `desktop/`: separate tsconfig roots, separate builds, and shortly a
separate repository. So it carries a generated copy.

THE DIGESTS ARE COPIED, NEVER RECOMPUTED, AND THAT IS THE WHOLE POINT

Recomputing them here from the website's own files would write down a checksum of this script's own
output. It would agree with every possible text, including a corrupted one, and pin nothing. Taking
the value out of `desktop/src/shared/legal.ts` means the website's test compares its copy against a
number a human committed in the same act as writing the words.
"""

import pathlib
import re

ROOT = pathlib.Path(__file__).resolve().parents[1]
LEGAL_TS = ROOT / "desktop/src/shared/legal.ts"
TARGET = ROOT / "apps/web/src/lib/legal.ts"

#: Everything from `const SECTIONS: Section[] = [` to this marker is what the digest covers.
SUB_COMPONENTS_MARKER = "// ── Sub-components"


def _digest(source: str, name: str) -> str:
    """A 64-hex constant, however it is wrapped. Prettier may put the value on its own line."""
    found = re.search(name + r'\s*=\s*\n?\s*"([0-9a-f]{64})"', source)
    if found is None:
        raise SystemExit(f"{name} is not declared as a 64-hex constant in {LEGAL_TS}")
    return found.group(1)


def _literal(source: str, name: str) -> str:
    found = re.search(name + r'\s*=\s*"([^"]+)"', source)
    if found is None:
        raise SystemExit(f"{name} is not declared in {LEGAL_TS}")
    return found.group(1)


HEADER = '''/**
 * GENERATED by `scripts/mirror_web_legal_constants.py`, via `scripts/sync_web_legal.py`.
 * Do not edit.
 *
 * The website publishes the application's legal documents, and these are how it checks that the
 * copy it publishes is the one that was written: a test here hashes this repository's own
 * `components/Legal/*.tsx` and compares. A copy that has drifted fails in THIS repository's CI,
 * without needing to read the application's tree — which it will not be able to do once the two are
 * separate repositories.
 *
 * The numbers are COPIED from the application, never recomputed from the files beside them. A
 * digest computed here would be a checksum of this repository's own content, which agrees with
 * every possible text and pins nothing.
 *
 * WHAT THIS CANNOT PROVE is that the DEPLOYED site serves the current version. Nothing in CI can,
 * without reaching the network. That is residual, and handled by publishing rather than by a test.
 */

/** The version registration records as accepted, and the date both documents print. */
export const TERMS_VERSION = "{terms_version}";
export const TERMS_DISPLAY_DATE = "{terms_display_date}";

/**
 * SHA-256 of each document's `SECTIONS` array: everything from `const SECTIONS: Section[] = [` up
 * to the `Sub-components` banner, with carriage returns removed.
 *
 * THE SCOPE IS NOT A DETAIL. The two copies legitimately differ OUTSIDE that range — this one
 * carries a "this is a copy" header, and a breadcrumb pointing at the site root rather than at the
 * application's Settings screen, which does not exist here. A digest over the whole file would
 * differ between the two by construction and could never agree.
 *
 * Carriage returns are stripped because two checkouts can disagree about line endings while the
 * words do not.
 */
export const PRIVACY_SECTIONS_SHA256 = "{privacy}";
export const TERMS_SECTIONS_SHA256 = "{terms}";
'''


def mirror() -> pathlib.Path:
    source = LEGAL_TS.read_text(encoding="utf-8")
    body = HEADER.format(
        terms_version=_literal(source, "TERMS_VERSION"),
        terms_display_date=_literal(source, "TERMS_DISPLAY_DATE"),
        privacy=_digest(source, "PRIVACY_SECTIONS_SHA256"),
        terms=_digest(source, "TERMS_SECTIONS_SHA256"),
    )
    TARGET.parent.mkdir(parents=True, exist_ok=True)
    TARGET.write_text(body, encoding="utf-8", newline="\n")
    return TARGET


if __name__ == "__main__":
    written = mirror()
    print(f"wrote {written.relative_to(ROOT).as_posix()}")
