"""Copy the application's legal documents onto the website.

Both places must publish them: the desktop app shows them where a person accepts them, so they ship
inside the binary and work offline; Stripe and any app store need a public URL, and a reader
deciding whether to install anything wants to read the terms first. Neither package can import from
the other — separate tsconfig roots, separate builds — so the website carries a copy.

`tests/test_marketing_pages.py` compares the two and fails on any difference, and this script is
what the failure tells you to run. Edit
`desktop/renderer/src/components/Legal/{PrivacyClient,TermsClient}.tsx` — the application's copy is
the original, because that is the one a person clicks "I agree" against — then:

    python scripts/sync_web_legal.py
"""

import pathlib

ROOT = pathlib.Path(__file__).resolve().parents[1]
DESKTOP = ROOT / "desktop/renderer/src/components/Legal"
WEB = ROOT / "apps/web/src/components/Legal"

HEADER = '''/**
 * ── A COPY, AND THE COPY IS THE POINT ─────────────────────────────────────────────────────────────
 *
 * This file is `desktop/renderer/src/components/Legal/{name}` with one change: the breadcrumb
 * points at the site root rather than at the application's Settings screen, which does not exist
 * here. `tests/test_marketing_pages.py` compares the two files' SECTIONS blocks and their
 * "Last updated" dates, and fails on any difference.
 *
 * WHY IT IS DUPLICATED AT ALL. Both places must publish it. The desktop app shows it in its
 * sign-up dialog, where a person accepts it — so it has to ship inside the binary and work offline.
 * Stripe and the app stores need a public URL, and a reader deciding whether to install anything
 * wants to read the terms first — so it has to be a web page. Neither can import from the other:
 * they are separate packages with separate tsconfig roots and separate build pipelines.
 *
 * WHAT IT REPLACED, because it is worth knowing how far this had drifted. The version here was
 * dated 1 January 2025 and described OAuth sign-in with Microsoft and Google, cookies for session
 * and CSRF tokens, analytics retained 90 days, and staff reviewing conversations for quality
 * assurance — none of which existed. The application's copy was rewritten twice since: once to
 * describe a local-first app, and again when the optional account arrived. This website was still
 * serving the 2025 text to the public, which is the copy Stripe and a prospective user would read.
 *
 * DO NOT EDIT THIS FILE. Edit the application's, then copy it here; the test names the command.
 */
'''


def sync(name: str) -> None:
    source = (DESKTOP / name).read_text(encoding="utf-8")

    # The application's breadcrumb goes to its Settings screen. On the website the equivalent is
    # the site itself.
    old_crumb = '''          <Link
            href="/profile"
            className="text-[11px] text-ink-3/60 hover:text-ink-2 transition-colors"
          >
            Settings
          </Link>'''
    new_crumb = '''          <Link
            href="/"
            className="text-[11px] text-ink-3/60 hover:text-ink-2 transition-colors"
          >
            VoidCode
          </Link>'''
    assert source.count(old_crumb) == 1, f"{name}: breadcrumb not found"
    source = source.replace(old_crumb, new_crumb)

    # Insert the "this is a copy" header after the "use client" directive.
    marker = '"use client";\n\n'
    assert source.startswith(marker), f"{name}: no leading use-client directive"
    source = marker + HEADER.format(name=name) + "\n" + source[len(marker) :]

    (WEB / name).write_text(source, encoding="utf-8", newline="\n")
    print(f"synced {name}")


for name in ("PrivacyClient.tsx", "TermsClient.tsx"):
    sync(name)
