"""add_courses_table

Revision ID: 3ac4f79184db
Revises: 93f288d0e905
Create Date: 2026-02-18 17:51:09.144942

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '3ac4f79184db'
down_revision: str | None = '93f288d0e905'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=True)
    op.create_index(op.f('ix_courses_order_index'), 'courses', ['order_index'], unique=False)
    op.add_column('problems', sa.Column('course_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_problems_course_id'), 'problems', ['course_id'], unique=False)
    op.create_foreign_key(None, 'problems', 'courses', ['course_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'problems', type_='foreignkey')
    op.drop_index(op.f('ix_problems_course_id'), table_name='problems')
    op.drop_column('problems', 'course_id')
    op.drop_index(op.f('ix_courses_order_index'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_table('courses')
    # ### end Alembic commands ###
