"""add_driver_code_to_code_templates

Revision ID: 9024b6255687
Revises: ac9a1b3b96f9
Create Date: 2026-02-11 06:47:21.336925

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9024b6255687'
down_revision: str | None = 'ac9a1b3b96f9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('code_templates', sa.Column('driver_code', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('code_templates', 'driver_code')
    # ### end Alembic commands ###
