"""add gpu credit wallet, reservations and ledger

Revision ID: a3f9c2e71b04
Revises: 6c5c1ed2861e
Create Date: 2026-09-10 00:12:00.000000

WRITTEN BY HAND, NOT AUTOGENERATED, AND THAT IS LOAD-BEARING HERE

Three of the things this migration creates are ones autogenerate does not emit correctly:

  * **The four CHECK constraints.** Alembic's autogenerate does not detect `CheckConstraint` at all
    by default -- it would have created these tables with the columns and silently without the
    invariants, which is the worst outcome available: the schema would look right and guarantee
    nothing.
  * **The partial index** `ix_gpu_reservations_held ... WHERE state = 'held'`. Autogenerate does not
    render `postgresql_where`, so the index would be created over every row instead of the held
    minority.
  * **The two enum types.** Postgres enums need creating before the table that uses them and
    dropping after, and autogenerate's handling of that in `downgrade()` is unreliable.

The head revision this follows (`6c5c1ed2861e`) documents the other reason: autogenerate against
this project emits pre-existing model/database drift as extra operations -- five of them last time,
including NOT NULLs that would fail against existing rows. A migration named for one change that
quietly performs six is unreviewable. This one creates three tables, two enums, four checks and two
indexes, and nothing else.

WHY THE CHECKS ARE WORTH THE PRECEDENT

There are no CHECK constraints anywhere else in this schema. These are the first. They exist because
this is the money path, and it is the one place where "the service should not oversell" and "the
database will not let it" are different guarantees. `ck_gpu_wallets_reserved_le_balance` is the
invariant the whole reservation design rests on; `ck_gpu_reservations_settled_le_hold` is the promise
that a learner is never charged more than was authorised before their request ran.
"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3f9c2e71b04'
down_revision: str | None = '6c5c1ed2861e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


# Named explicitly so `downgrade()` can drop them. An inline `sa.Enum` inside `create_table` would
# be created implicitly and then leak on the way back down.
reservation_state = postgresql.ENUM(
    'held', 'settled', 'voided', name='gpu_reservation_state_enum', create_type=False
)
ledger_entry_type = postgresql.ENUM(
    'grant', 'hold', 'release', 'charge', 'refund', 'adjust',
    name='gpu_ledger_entry_type_enum', create_type=False,
)


def upgrade() -> None:
    bind = op.get_bind()
    reservation_state.create(bind, checkfirst=True)
    ledger_entry_type.create(bind, checkfirst=True)

    # ── wallets ──────────────────────────────────────────────────────────────
    #
    # `balance_micro` is the TOTAL, including whatever is currently reserved. Modelling it that way
    # rather than as balance-excluding-reserved is what lets the reservation be a single guarded
    # UPDATE and what lets "you cannot reserve what you do not have" be a CHECK rather than
    # application logic. Available credit is `balance_micro - reserved_micro`.
    op.create_table(
        'gpu_wallets',
        # The user id IS the primary key: one wallet per user, needing no separate unique index.
        sa.Column('user_id', sa.UUID(), nullable=False),
        sa.Column('balance_micro', sa.BigInteger(), server_default='0', nullable=False),
        sa.Column('reserved_micro', sa.BigInteger(), server_default='0', nullable=False),
        sa.Column(
            'updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('user_id'),
        sa.CheckConstraint('balance_micro >= 0', name='ck_gpu_wallets_balance_nonneg'),
        sa.CheckConstraint('reserved_micro >= 0', name='ck_gpu_wallets_reserved_nonneg'),
        # The invariant the reservation design rests on. If this can be violated, a wallet has sold
        # credit it does not hold.
        sa.CheckConstraint(
            'reserved_micro <= balance_micro', name='ck_gpu_wallets_reserved_le_balance'
        ),
    )

    # ── reservations ─────────────────────────────────────────────────────────
    #
    # The settled row IS the per-request cost record. A parallel "requests" table would be a second
    # place for the same fact to drift.
    op.create_table(
        'gpu_reservations',
        # The idempotency anchor. Deliberately not `request_id`, which is client-visible and was not
        # unique until the commit before this one.
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('wallet_user_id', sa.UUID(), nullable=False),
        sa.Column('request_id', sa.String(length=64), nullable=False),
        # `chat` | `interview_grade`. Grading runs the same model on the same card, so leaving it
        # unmetered would make it free GPU.
        sa.Column('kind', sa.String(length=32), nullable=False),
        sa.Column('state', reservation_state, server_default='held', nullable=False),
        sa.Column('hold_micro', sa.BigInteger(), nullable=False),
        sa.Column('settled_micro', sa.BigInteger(), nullable=True),
        # Measured occupancy: semaphore acquire to release. Null while held.
        sa.Column('slot_ms', sa.Integer(), nullable=True),
        # The narrower interval around the backend call. Audit only, never billed -- it is the
        # evidence for whether `slot_ms` including the backend's own queue wait is acceptable.
        sa.Column('backend_ms', sa.Integer(), nullable=True),
        # Snapshotted, so a price change is never retroactive.
        sa.Column('rate_micro_per_slot_second', sa.BigInteger(), nullable=False),
        sa.Column('backend', sa.String(length=16), nullable=False),
        sa.Column('replica', sa.String(length=64), nullable=True),
        sa.Column(
            'created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.Column('settled_at', sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(['wallet_user_id'], ['gpu_wallets.user_id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id'),
        sa.CheckConstraint('hold_micro > 0', name='ck_gpu_reservations_hold_positive'),
        sa.CheckConstraint(
            'settled_micro IS NULL OR settled_micro >= 0',
            name='ck_gpu_reservations_settled_nonneg',
        ),
        # "A settle may never exceed its hold", as a constraint rather than an if-statement.
        sa.CheckConstraint(
            'settled_micro IS NULL OR settled_micro <= hold_micro',
            name='ck_gpu_reservations_settled_le_hold',
        ),
        # A held row has no settled amount and a finished one always has one, so "finished" cannot
        # be half-recorded by a crash between two writes.
        sa.CheckConstraint(
            "(state = 'held' AND settled_micro IS NULL)"
            " OR (state <> 'held' AND settled_micro IS NOT NULL)",
            name='ck_gpu_reservations_state_consistent',
        ),
    )
    # Partial: the recovery sweep only ever looks for old held rows, and held rows are the small
    # minority once traffic is real. Autogenerate would have indexed every row instead.
    op.create_index(
        'ix_gpu_reservations_held',
        'gpu_reservations',
        ['created_at'],
        postgresql_where=sa.text("state = 'held'"),
    )
    op.create_index(
        'ix_gpu_reservations_wallet_time', 'gpu_reservations', ['wallet_user_id', 'created_at']
    )

    # ── ledger ───────────────────────────────────────────────────────────────
    #
    # Append-only by convention, not yet by grant: the application connects as the schema owner, so
    # a real guarantee needs REVOKE UPDATE, DELETE against a separate migration role. Not done here,
    # and said plainly so nobody reads more assurance into the table than it carries.
    op.create_table(
        'gpu_ledger',
        # BigInteger identity rather than UUID: an audit needs a total order and a UUID has none.
        sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column('wallet_user_id', sa.UUID(), nullable=False),
        sa.Column('entry_type', ledger_entry_type, nullable=False),
        # Signed: charges negative, grants positive. Summing this column reconstructs the balance,
        # which is what makes the wallet row a checkable cache rather than the source of truth.
        sa.Column('amount_micro', sa.BigInteger(), nullable=False),
        sa.Column('balance_after_micro', sa.BigInteger(), nullable=False),
        sa.Column('reservation_id', sa.UUID(), nullable=True),
        sa.Column('idempotency_key', sa.String(length=128), nullable=False),
        sa.Column(
            'created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False
        ),
        sa.ForeignKeyConstraint(['wallet_user_id'], ['gpu_wallets.user_id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['reservation_id'], ['gpu_reservations.id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id'),
        # This is what makes every money path idempotent. Keys are derived, never generated
        # (`charge:{reservation_id}`), so a retried settle is refused by the database rather than by
        # a read-check-write the application has to get right under concurrency.
        sa.UniqueConstraint('idempotency_key', name='uq_gpu_ledger_idempotency_key'),
    )
    op.create_index('ix_gpu_ledger_wallet', 'gpu_ledger', ['wallet_user_id', 'id'])


def downgrade() -> None:
    # Inverse order: ledger references reservations references wallets.
    op.drop_index('ix_gpu_ledger_wallet', table_name='gpu_ledger')
    op.drop_table('gpu_ledger')
    op.drop_index('ix_gpu_reservations_wallet_time', table_name='gpu_reservations')
    op.drop_index('ix_gpu_reservations_held', table_name='gpu_reservations')
    op.drop_table('gpu_reservations')
    op.drop_table('gpu_wallets')
    # After the tables, or Postgres refuses to drop a type still in use.
    bind = op.get_bind()
    ledger_entry_type.drop(bind, checkfirst=True)
    reservation_state.drop(bind, checkfirst=True)
