"""add catalogue modules and daily challenge

Revision ID: ecbee765535a
Revises: d4e5f6a7b8c9
Create Date: 2026-07-28 23:08:11.457987

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ecbee765535a'
down_revision: str | None = 'd4e5f6a7b8c9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_questions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('domain', sa.Enum('ml', 'dl', 'cuda', 'maths', 'llm', 'vlm', name='interview_domain_enum'), nullable=False),
    sa.Column('difficulty', postgresql.ENUM('easy', 'medium', 'hard', name='difficulty_enum', create_type=False), nullable=False),
    sa.Column('companies', sa.JSON(), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('approach', sa.Text(), nullable=False),
    sa.Column('model_answer', sa.Text(), nullable=False),
    sa.Column('follow_ups', sa.JSON(), nullable=False),
    sa.Column('red_flags', sa.JSON(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interview_questions_domain'), 'interview_questions', ['domain'], unique=False)
    op.create_index(op.f('ix_interview_questions_order_index'), 'interview_questions', ['order_index'], unique=False)
    op.create_index(op.f('ix_interview_questions_slug'), 'interview_questions', ['slug'], unique=True)
    op.create_table('papers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('authors', sa.String(length=500), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('venue', sa.String(length=120), nullable=True),
    sa.Column('arxiv_id', sa.String(length=40), nullable=True),
    sa.Column('pdf_url', sa.Text(), nullable=False),
    sa.Column('abstract', sa.Text(), nullable=False),
    sa.Column('difficulty', postgresql.ENUM('easy', 'medium', 'hard', name='difficulty_enum', create_type=False), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('sections', sa.JSON(), nullable=False),
    sa.Column('key_equations', sa.JSON(), nullable=False),
    sa.Column('related_problem_slugs', sa.JSON(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_papers_order_index'), 'papers', ['order_index'], unique=False)
    op.create_index(op.f('ix_papers_slug'), 'papers', ['slug'], unique=True)
    op.create_table('projects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('kind', sa.Enum('llm', 'vlm', name='project_kind_enum'), nullable=False),
    sa.Column('difficulty', postgresql.ENUM('easy', 'medium', 'hard', name='difficulty_enum', create_type=False), nullable=False),
    sa.Column('categories', sa.JSON(), nullable=False),
    sa.Column('estimated_hours', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('steps', sa.JSON(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_projects_order_index'), 'projects', ['order_index'], unique=False)
    op.create_index(op.f('ix_projects_slug'), 'projects', ['slug'], unique=True)
    op.create_table('daily_deliveries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=False),
    sa.Column('opened_at', sa.DateTime(), nullable=True),
    sa.Column('consumed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['problem_id'], ['problems.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_deliveries_token_hash'), 'daily_deliveries', ['token_hash'], unique=True)
    op.create_index(op.f('ix_daily_deliveries_user_id'), 'daily_deliveries', ['user_id'], unique=False)
    op.create_table('interview_attempts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('question_id', sa.UUID(), nullable=False),
    sa.Column('self_rating', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('revealed_answer', sa.Boolean(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['interview_questions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'question_id', name='uq_interview_attempt')
    )
    op.create_index(op.f('ix_interview_attempts_question_id'), 'interview_attempts', ['question_id'], unique=False)
    op.create_index(op.f('ix_interview_attempts_user_id'), 'interview_attempts', ['user_id'], unique=False)
    op.create_table('paper_progress',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('paper_id', sa.UUID(), nullable=False),
    sa.Column('sections_read', sa.JSON(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['paper_id'], ['papers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'paper_id', name='uq_paper_progress')
    )
    op.create_index(op.f('ix_paper_progress_paper_id'), 'paper_progress', ['paper_id'], unique=False)
    op.create_index(op.f('ix_paper_progress_user_id'), 'paper_progress', ['user_id'], unique=False)
    op.create_table('project_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('current_step', sa.Integer(), nullable=False),
    sa.Column('completed_steps', sa.JSON(), nullable=False),
    sa.Column('step_state', sa.JSON(), nullable=False),
    sa.Column('artifacts', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_project_session')
    )
    op.create_index(op.f('ix_project_sessions_project_id'), 'project_sessions', ['project_id'], unique=False)
    op.create_index(op.f('ix_project_sessions_user_id'), 'project_sessions', ['user_id'], unique=False)
    # `problems.categories` was created as JSONB by revision d4e5f6a7b8c9 while
    # the model declared JSON — every autogenerate since has wanted to "fix" it.
    # It is also the only jsonb column in the schema; examples, constraints,
    # hints and test_cases.inputs are all json. Converting it settles the
    # mismatch in favour of the convention the rest of the codebase already uses.
    # The USING cast is required: Postgres will not coerce jsonb to json
    # implicitly.
    op.alter_column('problems', 'categories',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"),
               postgresql_using='categories::json')
    op.add_column('user_preferences', sa.Column('daily_enabled', sa.Boolean(), nullable=False))
    op.add_column('user_preferences', sa.Column('daily_send_hour', sa.Integer(), nullable=False))
    op.add_column('user_preferences', sa.Column('daily_timezone', sa.String(length=64), nullable=False))
    op.add_column('user_preferences', sa.Column('daily_last_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('user_preferences', sa.Column('daily_unsubscribe_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_preferences_daily_unsubscribe_token'), 'user_preferences', ['daily_unsubscribe_token'], unique=True)
    # `content_item_type_enum` was orphaned when the course hierarchy was
    # dropped in d4e5f6a7b8c9 — dropping a table does not drop the enum type it
    # used, and a leftover type blocks any later revision wanting that name.
    op.execute("DROP TYPE IF EXISTS content_item_type_enum")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_preferences_daily_unsubscribe_token'), table_name='user_preferences')
    op.drop_column('user_preferences', 'daily_unsubscribe_token')
    op.drop_column('user_preferences', 'daily_last_sent_at')
    op.drop_column('user_preferences', 'daily_timezone')
    op.drop_column('user_preferences', 'daily_send_hour')
    op.drop_column('user_preferences', 'daily_enabled')
    op.alter_column('problems', 'categories',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::jsonb"),
               postgresql_using='categories::jsonb')
    op.drop_index(op.f('ix_project_sessions_user_id'), table_name='project_sessions')
    op.drop_index(op.f('ix_project_sessions_project_id'), table_name='project_sessions')
    op.drop_table('project_sessions')
    op.drop_index(op.f('ix_paper_progress_user_id'), table_name='paper_progress')
    op.drop_index(op.f('ix_paper_progress_paper_id'), table_name='paper_progress')
    op.drop_table('paper_progress')
    op.drop_index(op.f('ix_interview_attempts_user_id'), table_name='interview_attempts')
    op.drop_index(op.f('ix_interview_attempts_question_id'), table_name='interview_attempts')
    op.drop_table('interview_attempts')
    op.drop_index(op.f('ix_daily_deliveries_user_id'), table_name='daily_deliveries')
    op.drop_index(op.f('ix_daily_deliveries_token_hash'), table_name='daily_deliveries')
    op.drop_table('daily_deliveries')
    op.drop_index(op.f('ix_projects_slug'), table_name='projects')
    op.drop_index(op.f('ix_projects_order_index'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_papers_slug'), table_name='papers')
    op.drop_index(op.f('ix_papers_order_index'), table_name='papers')
    op.drop_table('papers')
    op.drop_index(op.f('ix_interview_questions_slug'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_order_index'), table_name='interview_questions')
    op.drop_index(op.f('ix_interview_questions_domain'), table_name='interview_questions')
    op.drop_table('interview_questions')
        # Types created by this revision. Postgres keeps an enum after its last
    # table is dropped, so without this a re-upgrade fails on 'already exists'.
    op.execute("DROP TYPE IF EXISTS interview_domain_enum")
    op.execute("DROP TYPE IF EXISTS project_kind_enum")
    # ### end Alembic commands ###
